name: Build and Upload Assets

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Get tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Upload release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: build-${{ env.TAG_NAME }}
          tag: ${{ env.TAG_NAME }}
          workdir: .

      - name: Generate Zip
        run: |
          zip -r ${{ env.TAG_NAME }}>.zip . -x ".git/*" ".github/*"
      
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.TAG_NAME }}.zip
          asset_name: mything
          tag: ${{ env.TAG_NAME }}
          overwrite: true
